/*INSERT INTO COMPANY(CODE, NAME) VALUES('CP01', 'GS ITM');
INSERT INTO LOCATION (CODE, NAME, latitude, longitude) VALUES('LC01', '역삼 GS 타워', 37.50195492996154, 127.03732902930322);
INSERT INTO LOCATION (CODE, NAME, latitude, longitude) VALUES('LC02', '보헌 빌딩', 37.57838965148805, 126.98667257949424);
INSERT INTO LOCATION (CODE, NAME, latitude, longitude) VALUES('LC03', '원서 빌딩', 37.57917595553029, 126.98844416432452);

INSERT INTO COMPANY_LOCATION (company_id, location_id) VALUES(1,1);
INSERT INTO COMPANY_LOCATION (company_id, location_id) VALUES(1,2);
INSERT INTO COMPANY_LOCATION (company_id, location_id) VALUES(1,3);

INSERT INTO MEMBER(EMAIL, NAME, PASSWORD, CONTACT, DELETE_YN, PUSH_AGREE_YN, INSERT_DATE, UPDATE_DATE, LOGIN_FAIL_CNT, PASSWORD_MODIFIED_DATE, COMPANY_ID) VALUES('it1485@gsitm.com', '박다솜', '$2a$10$FmJYBn/KEoBx1dLkHHtE/ecxztVkQK9MyHIRhYv8c2u665sFmJ72O', '01082510613', 'N', 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP, 1);
INSERT INTO MEMBER_ROLE (ROLE, MEMBER_ID) VALUES('ROLE_MEMBER', '1');

INSERT INTO CODE(CODE, NAME, CODE_GROUP, CODE_ORDER, USE_YN) VALUES('AT01', '정상 출근', 'ATTEND', 1, 'Y');
INSERT INTO CODE(CODE, NAME, CODE_GROUP, CODE_ORDER, USE_YN) VALUES('AT02', '오전 반차', 'ATTEND', 2, 'Y');
INSERT INTO CODE(CODE, NAME, CODE_GROUP, CODE_ORDER, USE_YN) VALUES('AT03', '오후 반차', 'ATTEND', 3, 'N');
INSERT INTO CODE(CODE, NAME, CODE_GROUP, CODE_ORDER, USE_YN) VALUES('AT04', '오전 반반차', 'ATTEND', 4, 'Y');
INSERT INTO CODE(CODE, NAME, CODE_GROUP, CODE_ORDER, USE_YN) VALUES('AT05', '오후 반반차', 'ATTEND', 5, 'Y');
INSERT INTO CODE(CODE, NAME, CODE_GROUP, CODE_ORDER, USE_YN) VALUES('AT06', '휴가', 'ATTEND', 6, 'Y');
INSERT INTO CODE(CODE, NAME, CODE_GROUP, CODE_ORDER, USE_YN) VALUES('AT07', '재택 근무', 'ATTEND', 7, 'N');
INSERT INTO CODE(CODE, NAME, CODE_GROUP, CODE_ORDER, USE_YN) VALUES('AT08', 'pm', 'ATTEND', 8, 'Y');

INSERT INTO ATTEND(ATTEND_DATE, INSERT_DATE, MEMBER_ID) VALUES (FORMATDATETIME(DATEADD(Day ,-1, CURRENT_DATE),'yyyyMMdd'), CURRENT_TIMESTAMP, 1L);
INSERT INTO ATTEND(ATTEND_DATE, INSERT_DATE, MEMBER_ID) VALUES (FORMATDATETIME(CURRENT_DATE,'yyyyMMdd'), CURRENT_TIMESTAMP, 1L);
*/