-- INSERT INTO TB_USER(EMAIL, NAME, PASSWORD, CONTACT, EMPLOYEE_CODE, COMPANY_CODE, DEPARTMENT_CODE, DELETE_YN, PUSH_AGREE_YN, INSERT_DATE, UPDATE_DATE, LOGIN_FAIL_CNT, PASSWORD_MODIFY_DATE) VALUES('it1485@gsitm.com', '박다솜', '$2a$10$FmJYBn/KEoBx1dLkHHtE/ecxztVkQK9MyHIRhYv8c2u665sFmJ72O', '01082510613', 'it1485', 'C0001', 'D0001', 'N', 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP);
INSERT INTO COMPANY(CODE, NAME) VALUES('CP01', 'GS ITM');
INSERT INTO LOCATION (CODE, NAME, latitude, longitude) VALUES('LC01', '안국 본사', 127.037582, 37.502410);
INSERT INTO LOCATION (CODE, NAME, latitude, longitude) VALUES('LC02', 'GS 타워', 127.037582, 37.686532);
INSERT INTO COMPANY_LOCATION (company_id, location_id) VALUES(1,1);
INSERT INTO COMPANY_LOCATION (company_id, location_id) VALUES(1,2);

INSERT INTO USERS(EMAIL, NAME, PASSWORD, CONTACT, DELETE_YN, PUSH_AGREE_YN, INSERT_DATE, UPDATE_DATE, LOGIN_FAIL_CNT, PASSWORD_MODIFIED_DATE, COMPANY_ID) VALUES('it1485@gsitm.com', '박다솜', '$2a$10$FmJYBn/KEoBx1dLkHHtE/ecxztVkQK9MyHIRhYv8c2u665sFmJ72O', '01082510613', 'N', 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, CURRENT_TIMESTAMP, 1);
INSERT INTO USER_ROLE (ROLE, USER_ID) VALUES('ROLE_MEMBER', '1');

INSERT INTO CODE(CODE, NAME, CODE_GROUP, CODE_ORDER, USE_YN) VALUES('AC01', '정상 출근', 'ATTEND', 1, 'Y');
INSERT INTO CODE(CODE, NAME, CODE_GROUP, CODE_ORDER, USE_YN) VALUES('AC02', '오전 반차', 'ATTEND', 2, 'Y');
INSERT INTO CODE(CODE, NAME, CODE_GROUP, CODE_ORDER, USE_YN) VALUES('AC03', '오후 반차', 'ATTEND', 3, 'N');
INSERT INTO CODE(CODE, NAME, CODE_GROUP, CODE_ORDER, USE_YN) VALUES('AC04', '오전 반반차', 'ATTEND', 4, 'Y');
INSERT INTO CODE(CODE, NAME, CODE_GROUP, CODE_ORDER, USE_YN) VALUES('AC05', '오후 반반차', 'ATTEND', 5, 'Y');
INSERT INTO CODE(CODE, NAME, CODE_GROUP, CODE_ORDER, USE_YN) VALUES('AC06', '휴가', 'ATTEND', 6, 'Y');
INSERT INTO CODE(CODE, NAME, CODE_GROUP, CODE_ORDER, USE_YN) VALUES('AC07', '재택 근무', 'ATTEND', 7, 'N');
INSERT INTO CODE(CODE, NAME, CODE_GROUP, CODE_ORDER, USE_YN) VALUES('AC08', 'pm', 'ATTEND', 8, 'Y');

INSERT INTO ATTEND(ATTEND_DATE, INSERT_DATE, USER_ID) VALUES (FORMATDATETIME(DATEADD(Day ,-1, CURRENT_DATE),'yyyyMMdd'), CURRENT_TIMESTAMP, 1L);
INSERT INTO ATTEND(ATTEND_DATE, INSERT_DATE, USER_ID) VALUES (FORMATDATETIME(CURRENT_DATE,'yyyyMMdd'), CURRENT_TIMESTAMP, 1L);
